static char SA_vs_src[] =  
	"attribute vec4 a_position;									\n"
	"attribute vec4 a_normal;									\n"
	"attribute vec2 a_texcood;									\n"
	"attribute vec4 a_bone_ids;									\n"
	"attribute vec4 a_bone_weights;								\n"
	"uniform mat4	u_mvpMatrix;								\n"
	"uniform int	u_bone_count;								\n"
	"uniform mat4	u_bone_matrix[32];							\n"
	//"uniform mat4	u_bone_offset[32];							\n"
	"varying vec4	v_normal;									\n"
	"varying vec2	v_texcood;									\n"
	"void main()												\n"
	"{															\n"
	"	if (u_bone_count>0)										\n"
	"	{														\n"
	"		vec4 position = vec4(0,0,0,0);						\n"
	"		ivec4 bone_ids = a_bone_ids;						\n"
	"		for (int i=0; i<4; i++)								\n"
	"			position += u_bone_matrix[bone_ids[i]] * a_bone_weights[i] * a_position;	\n"
	"		gl_Position = u_mvpMatrix * position;				\n"
	"		v_normal = a_normal;								\n"
	"		v_texcood = a_texcood;								\n"
	"	}														\n"
	"	else													\n"
	"	{														\n"
	"		gl_Position = u_mvpMatrix * a_position;				\n"
	"		v_normal = a_normal;								\n"
	"		v_texcood = a_texcood;								\n"
	"	}														\n"
	"}															\n";

static char SA_fs_src[] =  
	"varying vec4 v_normal;										\n"
	"varying vec2 v_texcood;									\n"
	"uniform sampler2D s_texture;								\n"
	"void main()												\n"
	"{															\n"
	"	gl_FragColor = texture2D(s_texture,v_texcood);			\n"
	"}															\n";
